// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorTerm.DAL;

namespace TutorTerm.Migrations
{
    [DbContext(typeof(TutorContext))]
    partial class TutorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TutorTerm.DAL.Model.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Alpha")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("HexValue")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Name");

                    b.HasKey("ColorId");

                    b.ToTable("Color");

                    b.HasData(
                        new { ColorId = 1, Alpha = true, HexValue = "#0000FF", Name = "Blue" },
                        new { ColorId = 2, Alpha = false, HexValue = "#FF0000", Name = "Red" }
                    );
                });

            modelBuilder.Entity("TutorTerm.DAL.Model.Gender", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new { Id = (byte)1, Name = "male" }
                    );
                });

            modelBuilder.Entity("TutorTerm.DAL.Model.Language", b =>
                {
                    b.Property<short>("LanguageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("LanguageId");

                    b.ToTable("Language");

                    b.HasData(
                        new { LanguageId = (short)1, Code = "cs", Name = "czech" },
                        new { LanguageId = (short)2, Code = "pl", Name = "polski" },
                        new { LanguageId = (short)3, Code = "ru", Name = "русский" }
                    );
                });

            modelBuilder.Entity("TutorTerm.DAL.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("GenderId");

                    b.Property<short>("LanguageId");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasKey("UserId");

                    b.HasIndex("GenderId");

                    b.HasIndex("LanguageId");

                    b.ToTable("User");

                    b.HasData(
                        new { UserId = 1, GenderId = (byte)1, LanguageId = (short)3, Name = "Petr", Surname = "Veliký" }
                    );
                });

            modelBuilder.Entity("TutorTerm.DAL.Model.User", b =>
                {
                    b.HasOne("TutorTerm.DAL.Model.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TutorTerm.DAL.Model.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
